version: "3.8"
services:
  my_web_app:  
    container_name: "django_todo_app"
    build: .
    ports:
      - "8000:8000"  
    volumes:
      - django_todo_app:/app
  my_web_app_db:
    container_name: "my_sql_db"
    image: mysql:latest
    environment:
      MY_SQL_ROOT_PASSWORD: "test@123"
    ports:
    - "3306:3306"
  my_nginx_server:
    container_name: "nginx_server"
    image: nginx:latest
    ports:
      - "80:80"    
volumes:
    django_todo_app:    
